version: "3.7"

services:
  app_proxy:
    environment:
      # <app-id>_<web-service-name>_1
      APP_HOST: claudia-claude-gui_web_1
      APP_PORT: 8088

  web:
    # IMPORTANT: set this to YOUR pushed image. Example below assumes GHCR under your username.
    # For local testing a tag is OK; for PRs pin with @sha256:<multi-arch-digest>.
    image: ghcr.io/harmalh/claudia-claude-gui:1.0.0
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    environment:
      # noVNC listens on 8088 inside the container
      VNC_PASSWORD: ${APP_PASSWORD}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    # If you need persistence, uncomment:
    # volumes:
    #   - ${APP_DATA_DIR}/data:/data